### ISSUE TITLE
Question About Evaluation on the Middlebury v3 Benchamrk.

### ISSUE THREAD

**Issue by Zhaohuai-L** [David-Zhao-1997/High-frequency-Stereo-Matching-Network#4]
Hi @David-Zhao-1997 , 
Thank you very much for your great work.
I recently evaluated my method on Middlebury, but bothered by a error (listed bellow), even using the disparitys on the training set of the other method downloaded from the website.
So I'm wondering if you've encountered this problem when submitting before?
![image](https://github.com/David-Zhao-1997/High-frequency-Stereo-Matching-Network/assets/62138387/725ff6b9-de74-4821-a4a7-4f40ecc3eec1)

**Comment by David-Zhao-1997** [comment]
In my previous submissions, the problem did not occur, and there should be a problem with the recent Middlebury evaluation system. Presumably, based on the error reported in your screenshot, there is a problem with the database of the evaluation website.

**Comment by Zhaohuai-L** [comment]
Ok, thanks for your reply.
