### ISSUE TITLE
<corr_sampler> or <alt_cuda_corr> undefined

### ISSUE THREAD

**Issue by ghost** [David-Zhao-1997/High-frequency-Stereo-Matching-Network#7]
Hello,

when attempting run your model on own images, we cannot find corr_sampler in class CorrSampler file corr.py first called by CorrBlockFast1D. 

The try/except import at the top of the file is strange. What module is this, is this necessary?

**Comment by David-Zhao-1997** [comment]
When you run the program, make sure to set `--corr_implementation reg` or `--corr_implementation reg_cuda`

reg_cuda is an accelerated implementation of Correlation Volume provided in RAFT-Stereo. If you want to use it, you need to compile it before running the code. The method is as follows:
```
cd sampler
rm -r build corr_sampler.egg-info dist
python setup.py install && cd ...
```
alt_cuda_corr is deprecated in our method, and the new commit has removed the relevant code.

**Comment by ghost** [comment]
Thanks for the info, I got it to work. Maybe change the "(optional)" in the ReadMe to something else, because it seems required for every use case, at least to me.

**Comment by 2c984r83y** [comment]
> Thanks for the info, I got it to work. Maybe change the "(optional)" in the ReadMe to something else, because it seems required for every use case, at least to me.

To avoid using `corr_sampler`, you can change default set of `corr_implementation` from `reg_cuda` into `reg`
```python
parser.add_argument('--corr_implementation', choices=["reg", "reg_cuda"], default="reg",help="correlation volume implementation")`
```
