### ISSUE TITLE
Performance on SceneFlow

### ISSUE THREAD

**Issue by cnexah** [David-Zhao-1997/High-frequency-Stereo-Matching-Network#8]
Hi, thank you for your great work!
I have a question about the performance of the pre trained model on SceneFlow.

https://github.com/David-Zhao-1997/High-frequency-Stereo-Matching-Network/blob/c10475fe30ff198781ecc7c712c24c781ff05096/core/stereo_datasets.py#L147 
The above code samples 400 images as test set. 
So I was wondering if the results of SceneFlow in table 4 in the paper are evaluated on 400 images?
   
When I run the evaluate_stereo.py with  valid_iters = 32 and on all test images, I got the epe error: 0.53.

**Comment by David-Zhao-1997** [comment]
Yes, the evaluation results given in the paper are based on 400 images as test set. The test results using the full test set are the same as yours.

**Comment by cnexah** [comment]
I see. Thank you for your prompt reply!
